// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        return web;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvXC7hqfpWeVl5sIxpBetvubcUomBDVVU',
    appId: '1:1008303385014:web:c3c0683d4b14aca582f917',
    messagingSenderId: '1008303385014',
    projectId: 'finotes1',
    authDomain: 'finotes1.firebaseapp.com',
    storageBucket: 'finotes1.firebasestorage.app',
    measurementId: 'G-8PCWXZYNER',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBN_q8H7oxXRLPxXm2DScGAT9Bkrh66djc',
    appId: '1:1008303385014:android:789bab26c45ba12682f917',
    messagingSenderId: '1008303385014',
    projectId: 'finotes1',
    storageBucket: 'finotes1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYvdExOU_G17SUwGougTMfWytG0PPydWI',
    appId: '1:1008303385014:ios:971638ff5075d22e82f917',
    messagingSenderId: '1008303385014',
    projectId: 'finotes1',
    storageBucket: 'finotes1.firebasestorage.app',
    iosBundleId: 'com.example.dailypilot',
  );
}
